SET SERVEROUTPUT ON;
DECLARE
V_NOME VARCHAR2(50);
V_SOBRENOME VARCHAR2(50);
V_RM NUMBER(10) := 1;
V_QTD_A NUMBER (10);
BEGIN
SELECT COUNT(*)INTO V_QTD_A FROM ALUNO;

LOOP
    SELECT NOME INTO V_NOME FROM ALUNO WHERE RM LIKE V_RM || '%'; 
    DBMS_OUTPUT.PUT_LINE('NOME: ' || V_NOME || ' ' || V_SOBRENOME);
    V_RM := V_RM + 1;
EXIT WHEN V_RM > V_QTD_A; 
END LOOP;

END;